server {
    listen 80;
    server_name _;

    location = / {
        root /var/www/blog;
        try_files /index.html =404;
    }

    location / {
        root /var/www/blog;
        try_files $uri $uri/ /index.html =404;
    }
}

server {
    listen 81;
    server_name _;

    location = / {
        root /var/www/editor;
        try_files /index.html =404;
    }

    location / {
        root /var/www/editor;
        try_files $uri $uri/ /index.html =404;
    }
}
