server {
    listen 80;
    server_name _;
    charset utf-8;

    location /editor/ {
        alias /var/www/editor/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location /attachments/ {
        alias /var/www/attachments/;
        try_files $uri $uri/ =404;
    }

    location / {
        root /var/www/blog;
        try_files $uri $uri/ /index.html =404;
    }
}
